### ISSUE TITLE
Resolve relative URLs in document to absolute URLs

### ISSUE THREAD

**Issue by aaronpk** [snarfed/granary#100]
If my HTML feed contains relative image URLs such as `/image.png`, then it's rendered as-is in the Atom feed, so consumers of the Atom feed see a broken image because they resolve it to `https://granary-demo.appspot.com/image.png` instead of `https://aaronparecki.com/image.png`

**Comment by snarfed** [comment]
good point!

granary does currently set `xml:base` in the top-level `feed` element to the input URL, ie `https://aaronparecki.com` in your case, which [the atom spec supports and says clients should honor](http://atomenabled.org/developers/syndication/#aboutThisDocument). i know at least some clients do, e.g. newsblur. does your feed reader not honor it?

**Comment by snarfed** [comment]
example:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<feed xml:lang="en-US"
      xmlns="http://www.w3.org/2005/Atom"
      xmlns:activity="http://activitystrea.ms/spec/1.0/"
      xmlns:georss="http://www.georss.org/georss"
      xmlns:ostatus="http://ostatus.org/schema/1.0"
      xmlns:thr="http://purl.org/syndication/thread/1.0"
      xml:base="https://aaronparecki.com/">
<generator uri="https://github.com/snarfed/granary">granary</generator>
<id>https://aaronparecki.com/</id>
<title>User feed for Aaron Parecki</title>
```

**Comment by aaronpk** [comment]
ooh good catch! I was just looking at my feed in the browser! I'm surprised Chrome doesn't support that then. (I was actually testing out whether Mailchimp will support sending out an email newsletter from a granary feed, which I'm not sure it does, but that's a different issue.)

**Comment by snarfed** [comment]
tentatively closing. feel free to reopen if necessary!
