### ISSUE TITLE
add appropriate content-type headers for XML feed

### ISSUE THREAD

**Issue by aaronpk** [snarfed/granary#101]
When I view a granary feed in chrome, I see a lot of text. When I view other feeds, chrome renders it as an XML tree.

I see granary sets a content-type header of `text/xml` which I would have thought would work, but on a feed that looks right in the browser I see that the content type is `application/xml`.

Compare:

https://voxpelli.com/english.xml

![xml-feed](https://media.aaronpk.com/Screen-Shot-2017-01-21-12-25-20.png)

https://granary-demo.appspot.com/url?input=html&output=atom&url=https%3A%2F%2Fnews.indieweb.org%2Fen

![text](https://media.aaronpk.com/Screen-Shot-2017-01-21-12-25-37.png)

**Comment by snarfed** [comment]
interesting indeed. evidently `application/xml` is the official mime type, but `text/xml` is an official alias:
https://tools.ietf.org/html/rfc7303
https://www.iana.org/assignments/media-types/media-types.xhtml

...so arguably this is a chrome bug? might as well switch to `application/xml` though.
