### ISSUE TITLE
Recognize "audio" property of h-entry

### ISSUE THREAD

**Issue by aaronpk** [snarfed/granary#102]
It'd be great to recognize the "audio" property and set it as a media enclosure, which would be one step closer to being able to turn an h-feed into a podcast feed!

Example feeds:

* https://aaronparecki.com/tag/100daysofmusic
* https://aaronparecki.com/tag/this-week-podcast

**Comment by tantek** [comment]
Note that u-audio is already an official Proposed Addition to h-entry: http://microformats.org/wiki/h-entry#Proposed_Additions and one more consumer (e.g. granary in addition to p3k) would help bump it from Proposed to Draft!

More: https://indieweb.org/audio

**Comment by snarfed** [comment]
yes!

**Comment by snarfed** [comment]
done! e.g.: https://granary-demo.appspot.com/url?input=html&output=atom&url=https%3A%2F%2Faaronparecki.com%2Ftag%2Fthis-week-podcast
