### ISSUE TITLE
add an option to not include the location in the Atom content

### ISSUE THREAD

**Issue by aaronpk** [snarfed/granary#104]
Posts in my Atom feed have the location they're posted from included inside the Atom content. 

```
  <content type="xhtml">
  <div xmlns="http://www.w3.org/1999/xhtml">
OH: Your level of commitment to trolling the internet is admirable <a href="/tag/domainswap">#<span class="p-category">domainswap</span></a>
<p>  <span class="p-location h-card">
    <span class="p-name">Portland,
        Oregon,
        USA</span>
  </span>
</p>
  </div>
  </content>
```

While this makes sense for readers, so that you see this information in a feed reader, it doesn't look good when using the Atom feed for syndication, such as how micro.blog can import posts from an Atom feed. http://micro.blog/aaronpk

Maybe there could be a query string parameter on the granary URL that would prevent this from being included in the content? e.g.

`https://granary-demo.appspot.com/url?input=html&output=atom&url=http%3A%2F%2Faaronparecki.com%2Fnotes&omit_location=true`

**Comment by snarfed** [comment]
done! @aaronpk you can now add `&reader=false` to your granary URL to omit location.
