### ISSUE TITLE
Silly documentation point

### ISSUE THREAD

**Issue by jeremycherfas** [snarfed/granary#111]
ThinkUp seems to have, er, changed and SocialSafe's certificate has expired.

**Comment by snarfed** [comment]
hey, thanks! interested in sending a PR? you should be able to do it in github's web UI directly if you want, without touching the command line.

**Comment by jeremycherfas** [comment]
I'd love to, but I really don't know how, and searching is no help. Point me to instructions and I'll do my best.

**Comment by snarfed** [comment]
sure! https://help.github.com/articles/editing-files-in-another-user-s-repository/

**Comment by jeremycherfas** [comment]
Done. Thanks.
