### ISSUE TITLE
Include mf2 photo in Atom content?

### ISSUE THREAD

**Issue by aaronpk** [snarfed/granary#113]
I'm struggling with getting my photos to appear in Micro.blog using the Granary Atom feed. In my mf2, I explicitly don't include the photo in the `e-content`, which is how I want the HTML to work, and is acceptable markup for a [photo post](https://indieweb.org/photo).

Granary doesn't appear to do anything with the mf2 `photo` property, so my photos are missing from the Atom feed, and aren't making it into micro.blog.

Would it make sense to add an `<img class="u-photo">` tag inside the Atom content if the photo is not already in the content? I haven't quite thought through the full implications of this so the answer may be no.

**Comment by tantek** [comment]
And should granary do u-photo -> AS "photo" object automatically? or is that a separate issue? or is that part of implementing Post Type Discovery?

**Comment by aaronpk** [comment]
Are there any actual consumers of AS in Atom? Is that something even worth building and maintaining?

**Comment by snarfed** [comment]
i have to admit, i'm kind of dreading triaging this. :P

i can easily translate `u-photo` outside `e-content` to the `<img>` tag in Atom content, but i'm really not qualified to determine whether it's a good idea, or what side effects it would have. usually i just lean on you all and other standards experts in the community, and kinda blindly do what you say...but the fact that you seem uncertain yourselves, here and especially in the IRC discussion that motivated this, make me a bit nervous.

am i overthinking?

**Comment by snarfed** [comment]
lots more discussion in IRC today: https://chat.indieweb.org/dev/2017-08-10#t1502329691111000

**Comment by aaronpk** [comment]
The other option I'm hearing is adding the photo as an Atom enclosure, although it seems like the support of images as enclosures among Atom/RSS readers is debatable.

**Comment by snarfed** [comment]
thanks! understood. granary actually does generate enclosures for audio and video, but not images.

I'm currently leaning toward including u-photo in the content, and crudely attempting to de-dupe, maybe even just existence check for the image URL.

**Comment by manton** [comment]
My first thought was also that `u-photo` should go into the content, just because it will be the most compatible with existing RSS readers. I tested an image enclosure with Reeder (one of the most popular RSS readers for the Mac) and it appears to ignore it.

**Comment by snarfed** [comment]
narrowed down the thinking here a bit [in an IRC discussion w/@aaronpk today](https://chat.indieweb.org/dev/2017-08-11#t1502474343806000).

some mf2 properties are primarily _data_. `content` and `name` obviously, but also `photo`, as discussed here. readers would expect to see them visibly rendered in the post.

other mf2 properties are primarily _metadata_. `published`, `updated`, `url`, `uid` are examples. also usually `location`, as discussed in #104. readers may expect to see these rendered outside the post, but not directly in the post content, in e.g. readers.

it may be obvious to us which properties are data vs metadata, at least mostly, but we don't yet have an explicit breakdown. that seems like an important need.

it may not be easy, of course. we may not have consensus on all properties, e.g. tags. other properties may be data sometimes but not other times, e.g. location in checkins.

also, except maybe for checkins)

**Comment by snarfed** [comment]
reopening due to a bug that @gregorlove reported: de-duping doesn't handle relative URLs. e.g.:

```html
 <p>The new Stavesacre is here! The new Stavesacre is here!</p> <p><img alt="" class="u-photo util-max-full-width" src="/site/assets/files/4560/new-phonebook.gif"/></p> 

<blockquote>
<img class="u-photo" src="https://gregorlove.com/site/assets/files/4560/new-phonebook.gif" alt="" />
</blockquote>
```

should be an easy fix. thanks again @gregorlove!
