### ISSUE TITLE
"Z" added to datetime with explicit offset

### ISSUE THREAD

**Issue by gRegorLove** [snarfed/granary#126]
On my [notes stream](https://gregorlove.com/notes/) I author datetimes like "2018-01-15 13:03-0800". Running that through Granary for an Atom feed is adding a "Z" at the end. [Example](https://granary.io/url?input=html&output=atom&url=http://gregorlove.com/notes/). I believe my datetime format is valid ISO 8601.

It appears to be doing [the same with my homepage](https://granary.io/url?input=html&output=atom&url=https://gregorlove.com/), which currently has slightly different ISO 8601 date formats ("T" separator, seconds, colon in offset)

**Comment by snarfed** [comment]
thanks for reporting! I'll look soon.

**Comment by snarfed** [comment]
fixed. thanks again!
