### ISSUE TITLE
JSONFeed is including a title when it shouldn't be

### ISSUE THREAD

**Issue by aaronpk** [snarfed/granary#128]
My Microformats->JSONFeed conversion is resulting with a title for one of the posts that shouldn't have had a title. The title and content match in the JSONFeed too. Here's the post permalink: https://aaronparecki.com/2018/01/18/20/

**Comment by snarfed** [comment]
thanks for filing!

looks like this is happening because of implied p-name from the mf2 parser. just to confirm, you'd expect this conversion to use our standard "is name a title?" logic and only use it if it differs meaningfully from content, right?

**Comment by aaronpk** [comment]
Yeah exactly. It's unfortunate that with Microformats everything has to have a name, but here we are. Granary can do the "is name different from the content" check and omit the name from the JSONFeed if it's the same.
