### ISSUE TITLE
Instagram->HTML: photos with no caption are missing a blank name property

### ISSUE THREAD

**Issue by aaronpk** [snarfed/granary#131]
Currently when there is no caption on a photo, there is no `p-name` class set, so the Microformats parser ends up with an implied name that includes all the "liked by ___" junk. Simple fix is to include an empty `p-name` element so that the consumer will see the blank name property.

![screenshot 2018-02-15 12 42 16](https://user-images.githubusercontent.com/113001/36279969-ab2651d4-124d-11e8-82c4-17b50aa191cd.png)

**Comment by snarfed** [comment]
🎵 _hello implied `p-name` our old friend...you've come to haunt us once again..._ 🎵

[discussed in IRC.](https://chat.indieweb.org/dev/2018-02-15#t1518731520582600) evidently this is a good example of how the original implied `p-name` rules were problematic and overly aggressive. they're working on toning them down in microformats/microformats2-parsing#6. so this would hopefully be a temporary measure (in standards timeframes 😆) until the new rules are settled and implemented. sgtm!

**Comment by snarfed** [comment]
@kartikprabhu says https://github.com/kartikprabhu/mf2py/tree/implied-name-fix might fix this!

**Comment by snarfed** [comment]
@kartikprabhu i tried that branch just now, and it works great! e.g. on https://granary.io/instagram/kevinmarks/@self/@app/BfTlf3xBF2A?format=html , it omits `name` on the top-level item, while current https://github.com/tommorris/mf2py pulls in the full junk string that @aaronpk described in this issue. thank you!

personally, other than that, the main mf2py issue i'd love to see happen is https://github.com/tommorris/mf2py/issues/83 . with that, and officially moving the repo to the microformats org, i'd be very happy!

**Comment by snarfed** [comment]
...also, of course, i've now realized that while this mf2py feature is great, it doesn't actually quite fix this issue, since this is on the consuming side, where i don't control the parser.

@aaronpk, depending on your usage, you might consider asking granary for `format=mf2-json` instead of `format=html`, since that won't have this problem! i'm guessing you reported this on behalf of someone else who's seeing granary html output in a feed reader, though, so you don't have that luxury either.

adding blank `p-name` is totally reasonable. will do.

**Comment by kartikprabhu** [comment]
@snarfed  thanks for testing. I think with mf2py not including the `p-name` the consumer can then assume that there is no `name` and hence it is blank?

**Comment by snarfed** [comment]
@kartikprabhu definitely! mf2py consumers at least.

**Comment by aaronpk** [comment]
That's great news! And yes, I was specifically asking for the blank p-name property to be added to the HTML so that parsers that haven't updated for the new implied name parsing rules will still get a result that looks good.

**Comment by kartikprabhu** [comment]
@snarfed just so you know I have moved all experimental coding ( basically things not officially in the mf2 spec ) to https://github.com/kartikprabhu/mf2py/tree/experimental
