### ISSUE TITLE
possible cache leak

### ISSUE THREAD

**Issue by snarfed** [snarfed/granary#135]
granary serves some feeds that are moderately high traffic, e.g. @aaronpk's and @gregorlove's (hi!), so it currently caches responses for 5m to avoid hammering their sites.

@aaronpk noticed a possible cache leak: he tried a twitter search for one query, then another, and got the same results as the first. maybe we're excluding search query from the cache key? seems unlikely since we cache the full url, but still.

**Comment by snarfed** [comment]
i should also mention `&cache=false` in the UI. (it's [in the docs](https://github.com/snarfed/granary#using-the-rest-api), but still.)

**Comment by cleverdevil** [comment]
This is happening to me, FWIW, on my Instagram feed that I am pulling from granary.io.

**Comment by snarfed** [comment]
ugh, sorry! definitely need to figure out and fix this, since there's likely some private data in the leaks.

**Comment by snarfed** [comment]
thanks again for reporting @aaronpk @cleverdevil, and apologies for the leak! deployed the fix.
