### ISSUE TITLE
RSS input

### ISSUE THREAD

**Issue by snarfed** [snarfed/granary#137]
corollary to #124 (RSS output). implicitly requested by @EdwardHinkle in https://chat.indieweb.org/2018-02-22#t1519317703184100

@kevinmarks's http://www.unmung.com/ already does it! source: https://github.com/kevinmarks/unmung

**Comment by kevinmarks** [comment]
Does granary use feedparser?

**Comment by snarfed** [comment]
@kevinmarks for atom input? nah, ElementTree.

https://github.com/snarfed/granary/blob/b6cbf7c46f1814953c8b8d448bf5a718cdc26343/granary/atom.py#L171-L294

**Comment by snarfed** [comment]
Looking at feedparser for this. One nice feature is that it normalizes across feed formats, so we can theoretically use the same code to handle both RSS and Atom input: https://feedparser.readthedocs.io/en/latest/content-normalization.html

**Comment by snarfed** [comment]
Done! With feedparser, naturally, thanks @kevinmarks!
