### ISSUE TITLE
Filter out repost/retweets

### ISSUE THREAD

**Issue by EdwardHinkle** [snarfed/granary#138]
It would be great to have a way to tell granary through the API that I only want original posts back, not retweets. Retweeting on Twitter is so common now it creates a ton of excess noise.

(Originally posted at https://eddiehinkle.com/2018/02/22/18/reply/)

**Comment by snarfed** [comment]
agreed! you can do this now in the library. i'm guessing you mean the REST API or web UI?

**Comment by snarfed** [comment]
er, nm, i see the _through the API_ now. will do!

**Comment by snarfed** [comment]
@EdwardHinkle and @aaronpk are now both filtering out retweets in Aperture, https://aaronparecki.com/2018/03/03/16/ , and implementing it here wouldn't be quite so easy as passing through query params to `get_activities`'s `fetch_*`, since those only control _extra_ API calls...so i'm deprioritizing this a bit. happy to reprioritize it if anyone else still wants it.

**Comment by snarfed** [comment]
i just noticed that you can turn off retweets from individual people in your twitter feed. on web, click on the three dots menu button on their profile, _Turn off Retweets_. more in https://help.twitter.com/en/using-twitter/retweet-faqs , _How do I turn Retweets off?_ section.

(PRs also always welcome! 😁 https://github.com/snarfed/granary/#development )

**Comment by snarfed** [comment]
[recent conversation in #-dev on how readers/consumers may be a better place for this than granary.](https://chat.indieweb.org/dev/2019-05-22#t1558546555852700) eg that's where @EdwardHinkle is doing this now.

**Comment by edent** [comment]
I'm trying to work out how to do it in the WordPress plugin I use: https://github.com/pfefferle/wordpress-webmention/issues/243

**Comment by snarfed** [comment]
added this to the library in 6d5a5079926368ecce631f15cf487ff131e9f405. Planning to expose it in twitter-atom and maybe granary with a query param.

**Comment by snarfed** [comment]
Done! add `&shares=false` to a granary REST API URL to filter out retweets.
