### ISSUE TITLE
Weirdness with categories in mf2 output

### ISSUE THREAD

**Issue by sknebel** [snarfed/granary#141]
https://granary.io/url?input=html&output=mf2-json&url=https%3A%2F%2Faaronparecki.com%2F2018%2F03%2F14%2F3%2F

turns html with mf2 like 
```html
<li class="h-entry">
…
<a href="/tag/spotify" class="p-category">spotify</a>
</li>
```
into 
```json
      "type": [
        "h-entry"
      ], 
      "properties": {
        "category": [
          {
            "type": [
              "u-category"
            ], 
            "properties": {
              "name": [
                "spotify"
              ]
            }
          }
        ], 
```
which looks like it's trying to build some kind of nested object for the category?

**Comment by snarfed** [comment]
interesting! yeah that should probably be a plain string and not a nested object, like how http://pin13.net/mf2/?url=https%3A%2F%2Faaronparecki.com%2F2018%2F03%2F14%2F3%2F does it.

given the prevalence of mf2 parsers, html -> mf2 json is a rare use case for granary, so I'm not surprised it has warts like this... but still, easily fixable. thanks for filing!
