### ISSUE TITLE
JSON Feed entries are not formatted like Atom entries

### ISSUE THREAD

**Issue by bdesham** [snarfed/granary#148]
(This is along the same lines as #146.)

When Granary turns Instagram posts into Atom entries, it’s smart about converting `\n\n` to `<p>` tags, hyperlinking usernames, and so on. Right now it seems that this kind of processing is not being done for JSON Feeds. I think Granary should put the same value in a JSON Feed’s `content_html` that it would have put in an Atom feed’s `content`.

I’d be willing to work on a patch for this (although I don’t have a *ton* of time in which to do so). What do you think is the best architectural approach to be able to specify the AS-to-HTML conversion in just one place?

**Comment by snarfed** [comment]
hey @bdesham, thanks for volunteering for this! this should actually be pretty easy, and is maybe just an embarrassing oversight. the hard work should already be extracted out and available in [`microformats2.render_content`](https://granary.readthedocs.io/en/latest/source/granary.html#granary.microformats2.render_content), you may just need to call that in `jsonfeed`.  example usage in `atom.py` (but no need to escape `&`s in json feed):

https://github.com/snarfed/granary/blob/master/granary/atom.py#L358-L360

most of the work may actually end up just updating the tests. :P

**Comment by snarfed** [comment]
thanks again @bdesham!
