### ISSUE TITLE
Atom titles when parsing microformats, 'note' type

### ISSUE THREAD

**Issue by swentel** [snarfed/granary#150]
So, this is more a support request. I'm trying to integrate with fediverse and want to expose an atom feed from my microformats page.

https://granary.io/url?url=https://realize.be/timeline&input=html&output=atom

It's almost good, apart from two things I can't put my finger on:

1. the title for entries which are 'note' posts. They do not include a 'p-name' class as that shouldn't be there normally. That's something that Aaron told me. However, when looking at his page, for his notes, he does include the p-name class, but on the same wrapper where there's also e-content, so maybe I should start doing that as well, because now, what you see, is that the entry titles in the atom feed contain too much garbage. It includes content which seems to be extracted from the node__meta class inside my feed. I remember I've seen this in the logs with brid.gy as well when publishing, but it's ok there. Is there a workaround for this that would only affect the atom feed by not the microformats parsing (e.g. http://xray.p3k.io/parse?expect=feed&url=https%3A%2F%2Frealize.be%2Ftimeline is fine)

2. The main title of the feed. For Aaron, the nicely says 'User feed for Aaron Parecki', mine uses the title from the first entry it seems. So I wonder what I missing here. 

Feel free to ping me on IRC on one of the indieweb channels if I'm there, it's probably easier, and I can do live tests then as well :)

**Comment by swentel** [comment]
Actually, scratch this issue, I'm going to use a simple php atom generator.

I'm sorry for bothering :)

**Comment by snarfed** [comment]
thanks for filing! and apologies again for the trouble.

[we discussed a bit on IRC.](https://chat.indieweb.org/dev/2018-05-25#t1527257386344100) at least some of this is probably due to mf2py bugs and missing features. see #142 and #145 for similar issues.

i'm currently working on upgrading to the recent mf2py 1.1.0 release, which fixes a few things. we'll see if that helps!

**Comment by swentel** [comment]
No worries about the troubles :)

I've put the p-name on the same wrapper now as e-content for 'notes' in the Drupal, so that's at least much better now. Looking for feed name now. Will reply here as well when found, so people experiencing the same can have pointers.

**Comment by swentel** [comment]
So regarding the feed title: if you put a p-name inside the h-feed container, it will take that as the feed title. example at https://realize.be/timeline - hardcoded right now, need to make this configurable still in the drupal plugin, but at least we know how to make it work :)
