### ISSUE TITLE
granary.xyz fails when logging into GitHub (it expects granary.io)

### ISSUE THREAD

**Issue by EdwardHinkle** [snarfed/granary#154]

**Comment by snarfed** [comment]
hey, thanks for the nudge! i haven't really launched or started using granary.xyz yet, and sadly, github [only allows (at best) a single domain in their redirect URL whitelist](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#redirect-urls), so i guess i'll change this if/when i'm ready to fully migrate everyone to .xyz. i'll keep this open until then.

**Comment by snarfed** [comment]
it's been a couple years, and i still haven't prioritized this migration, so i'm closing for now. il'll make sure this works if/when i do migrate.
