### ISSUE TITLE
Atom output doesn't create a summary from an h-feed

### ISSUE THREAD

**Issue by kevinmarks** [snarfed/granary#157]
https://granary.io/url?input=html&output=atom&url=http%3A%2F%2Fkevinmarks.com

whereas as1-xml does

https://granary.io/url?input=html&output=as1-xml&url=http%3A%2F%2Fkevinmarks.com

**Comment by snarfed** [comment]
hey kevin! thanks for the nudge.

i don't actually see that `atom:feed` allows an `atom:summary` element. am i misreading the spec? https://tools.ietf.org/html/rfc4287#page-12

**Comment by kevinmarks** [comment]
Sorry, I meant an atomSummary for the atom:entry, though h-feed summary maps to atom:feed atomSubtitle

**Comment by snarfed** [comment]
Done!
