### ISSUE TITLE
Twitter max video size has changed

### ISSUE THREAD

**Issue by sknebel** [snarfed/granary#162]
According to https://developer.twitter.com/en/docs/media/upload-media/uploading-media/media-best-practices, it seems like Twitter now supports video up to 512 MB(!). I suppose downstream users might limit earlier, but granary source still references a 15 MB limit.

https://github.com/snarfed/granary/blob/64df34a644a967cf0d76067b907aa5c07a7b53a1/granary/twitter.py#L100

**Comment by snarfed** [comment]
thanks for filing! fixed, and deployed to bridgy. (untested. :trollface:)

**Comment by snarfed** [comment]
also ideally twitter would publish this number in https://developer.twitter.com/en/docs/developer-utilities/configuration/api-reference/get-help-configuration and keep it updated there, so i could load it dynamically and not have to maintain it as a constant in my own code. they already have a `photo_size_limit` value there. sadly it seems like that API endpoint hasn't been updated in years, so i'm not holding my breath.
