### ISSUE TITLE
MF2-Atom missing published/updated dates

### ISSUE THREAD

**Issue by alexmingoia** [snarfed/granary#163]
Using granary.io on aaronparecki.com (@aaronpk) is failing to parse the dt-published fields and include them in the atom feed.

https://granary.io/url?input=html&output=atom&url=https%3A//aaronparecki.com/&hub=https%3A//switchboard.p3k.io/

**Comment by snarfed** [comment]
thanks for the nudge! not sure what happened there, but redeploying master fixed it.
