### ISSUE TITLE
Support mime type for mf2

### ISSUE THREAD

**Issue by dshanske** [snarfed/granary#165]
When returning mf2 json, return type application/mf2+json instead of application/json

**Comment by snarfed** [comment]
interesting idea! easy to do.

does application/mf2+json exist? [google doesn't find it anywhere.](https://www.google.com/search?client=firefox-b-1-d&q=%22application%2Fmf2%2Bjson%22) did you make it up?

out of curiosity, what's your use case?

**Comment by dshanske** [comment]
https://indieweb.org/rel-alternate

**Comment by dshanske** [comment]
I found a reference here on a google search...it saves me from differentiating between jsonfeed, which uses application/json and mf2 json

**Comment by dshanske** [comment]
@aaronpk Do you know how well adopted it is?

**Comment by dshanske** [comment]
I know Semantic Linkbacks uses it also

**Comment by snarfed** [comment]
thanks @dshanske! also http://microformats.org/wiki/microformats2-mime-type . guess i shouldn't have blindly trusted google's "No results found." :trollface:

**Comment by dshanske** [comment]
I am not sure about the Microformats wiki entry only because it is 4 years old. Not sure what may have evolved
