### ISSUE TITLE
Consider supporting head requests

### ISSUE THREAD

**Issue by dshanske** [snarfed/granary#166]
My code makes a head request to a URL. Granary doesn't support HEAD.

**Comment by snarfed** [comment]
sorry for the trouble!

the difficulty with this is that i need to make an external HTTP request, sometimes more than one, before i know which HTTP status code i can return. HEADs are supposed to be light, and granary already gets a lot of HEAD traffic (mostly from low quality bots) that i'd rather not start serving and absorbing that load for.

i'm open to ideas! having said that, pretty much all other feed readers handle granary's lack of HEAD fine. if you use the content-type from it, consider just falling back to GET, and check its returned content type if you need to?

**Comment by dshanske** [comment]
That's fine. I am already coding around it

**Comment by snarfed** [comment]
thanks! closing for now. feel free to reopen!
