### ISSUE TITLE
Potential dependency conflicts between granary and urllib3

### ISSUE THREAD

**Issue by NeolithEra** [snarfed/granary#168]
Hi, _**granary**_ directly and transitively introduced multiple versions of urllib3.

As shown in the following full dependency graph of **_granary_**, granary directly requires _**urllib3 >=1.14**, while the installed version of **_requests_**, **_mf2py_** and **_oauth-dropins_** require _**urllib3>=1.21.1,<1.26**_. 

According to Pip's “first found wins” installation strategy, _**urllib3 1.25.3**_ is the actually installed version.  

Although the first found package version _**urllib3 1.25.3**_ just satisfies the later dependency constraint (_**urllib3>=1.21.1,<1.26**_), it will lead to a build failure once developers release a newer version of urllib3.

### Dependency tree--------
```
granary(version range:)
| +-beautifulsoup4(version range:)
| +-brevity(version range:>=0.2.17)
| +-feedgen(version range:>=0.7.0)
| | +-lxml(version range:)
| | +-python-dateutil(version range:)
| +-future(version range:)
| +-html2text(version range:)
| +-jinja2(version range:)
| +-mf2py(version range:>=1.1.2)
| | +-html5lib(version range:>=1.0.1)
| | +-requests(version range:>=2.18.4)
| | | +-chardet(version range:>=3.0.2,<3.1.0)
| | | +-idna(version range:>=2.5,<2.9)
| | | +-urllib3(version range:>=1.21.1,<1.26)
| | | +-certifi(version range:>=2017.4.17)
| | +-BeautifulSoup4(version range:>=4.6.0)
| +-mf2util(version range:>=0.5.0)
| +-oauth-dropins(version range:>=1.14)
| | +-future(version range:>=0.16.0)
| | +-gdata(version range:>=2.0.18)
| | +-google-api-python-client(version range:>=1.7.4)
| | | +-httplib2(version range:>=0.9.2,<1dev)
| | | +-google-auth(version range:>=1.4.1)
| | | +-google-auth-httplib2(version range:>=0.0.3)
| | | +-six(version range:>=1.6.1,<2dev)
| | | +-uritemplate(version range:>=3.0.0,<4dev)
| | +-httplib2(version range:)
| | +-humanize(version range:)
| | +-oauth2client(version range:>=4.1.1)
| | | +-httplib2(version range:>=0.9.1)
| | | +-pyasn1(version range:>=0.1.7)
| | | +-pyasn1-modules(version range:>=0.0.5)
| | | +-rsa(version range:>=3.1.4)
| | | +-six(version range:>=1.6.1)
| | +-oauthlib(version range:)
| | +-python-tumblpy(version range:)
| | | +-requests(version range:>=1.2.2)
| | | | +-chardet(version range:>=3.0.2,<3.1.0)
| | | | +-idna(version range:>=2.5,<2.9)
| | | | +-urllib3(version range:>=1.21.1,<1.26)
| | | | +-certifi(version range:>=2017.4.17)
| | | +-requests_oauthlib(version range:>=0.3.2)
| | +-requests(version range:>=2.10.0)
| | | +-chardet(version range:>=3.0.2,<3.1.0)
| | | +-idna(version range:>=2.5,<2.9)
| | | +-urllib3(version range:>=1.21.1,<1.26)
| | | +-certifi(version range:>=2017.4.17)
| | +-requests-oauthlib(version range:)
| | +-requests-toolbelt(version range:>=0.6.2)
| | +-tweepy(version range:>=3.0)
| | | +-PySocks(version range:>=1.5.7)
| | | +-requests(version range:>=2.11.1)
| | | | +-chardet(version range:>=3.0.2,<3.1.0)
| | | | +-idna(version range:>=2.5,<2.9)
| | | | +-urllib3(version range:>=1.21.1,<1.26)
| | | | +-certifi(version range:>=2017.4.17)
| | | +-requests_oauthlib(version range:>=0.7.0)
| | | +-six(version range:>=1.10.0)
| | +-beautifulsoup4(version range:)
| | +-mf2py(version range:>=1.1.2)
| | | +-html5lib(version range:>=1.0.1)
| | | +-requests(version range:>=2.18.4)
| | | | +-chardet(version range:>=3.0.2,<3.1.0)
| | | | +-idna(version range:>=2.5,<2.9)
| | | | +-urllib3(version range:>=1.21.1,<1.26)
| | | | +-certifi(version range:>=2017.4.17)
| | | +-BeautifulSoup4(version range:>=4.6.0)
| | +-mf2util(version range:)
| | +-urllib3(version range:>=1.14)
| +-requests(version range:>=2.10.0)
| | +-chardet(version range:>=3.0.2,<3.1.0)
| | +-idna(version range:>=2.5,<2.9)
| | +-urllib3(version range:>=1.21.1,<1.26)
| | +-certifi(version range:>=2017.4.17)
| +-requests-toolbelt(version range:>=0.6.2)
| +-urllib3(version range:>=1.14)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution
1.	Fix your direct dependencies to be **_urllib3>=1.21.1,<1.26_** and **_requests==2.22.0_**, to remove this conflict. 
    I have checked this revision will not affect your downstream projects now.

2.	As multiple versions of urllib3 in your project, a better solution is changing _**urllib3**_ to be _**>=1.21.1,<1.26**_.


@    May I pull a request to solve this issue?

Build a good dependency ecosystem for python projects is our common goal ^_^.

**Comment by snarfed** [comment]
thanks for the thought! (looks like this was automated.)

i understand the problem. i'm reluctant to pin dependencies more strictly to exact versions like this, though, since i then have to update those pinned versions every time each dependency puts out a new release...and remember why i pinned in the first place, and resolve conflicts, etc.

requests themselves have discussed this issue (restricting their urllib3 version) before, multiple times: https://github.com/psf/requests/pull/4674, https://github.com/psf/requests/pull/4675, https://github.com/psf/requests/issues/4203. their solution is generally to update their urllib3 version restriction and cut a new release quickly each time. i'm going to stick with that for now. thanks again though!
