### ISSUE TITLE
convert mf2 length and size properties to RSS duration and length

### ISSUE THREAD

**Issue by snarfed** [snarfed/granary#169]
...except we have no clear mf2 standard yet for either one. discussion: https://chat.indieweb.org/dev/2019-08-08#t1565286782453800

https://indieweb.org/podcast shows two examples in the wild with `length`: aaronpk's is integer seconds, @gRegorLove's is `PT1H7M59S`. (what even is that?)

...and two examples with `size`, different human-readable versions: @aaronpk's `17.43mb`, @gRegorLove's `62.2 MB`.

RSS spec for `length` (integer bytes): http://www.rssboard.org/rss-specification#ltenclosuregtSubelementOfLtitemgt

iTunes details for `duration` (integer seconds): https://help.apple.com/itc/podcasts_connect/#/itc2b3780e76 , and example RSS: https://help.apple.com/itc/podcasts_connect/#/itcbaf351599

cc @jgmac1106

**Comment by Zegnat** [comment]
> @gRegorLove's is `PT1H7M59S`. (what even is that?)

[An ISO 8601 duration](https://en.wikipedia.org/wiki/ISO_8601#Durations): `PnYnMnDTnHnMnS`. Or more likely the derived [HTML duration syntax](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#durations). Though it is basically the same here. (I’d also argue it should have used a `<time>` element, but that’s a separate issue 😉 )

I feel like this has been discussed as mf2 properties, but can’t seem to find anything right now.

**Comment by dshanske** [comment]
mf2 duration is iso8601 duration in my humble opinion. Agree on size having no standard

**Comment by Zegnat** [comment]
> https://indieweb.org/podcast shows two examples in the wild with `length`: aaronpk's is integer seconds _[…]_

Where does @aaronpk do this? When I look at [Percolator](https://percolator.today/) it uses `p-duration`:

```html
<div class="podcast-meta">
  <a href="/episode/24" class="u-url">
    <time class="dt-published" datetime="2019-06-13">
      June 13, 2019
    </time>
  </a>
  &nbsp;&nbsp;•&nbsp;&nbsp; 
  <data class="p-duration" value="875">
    14m35s
  </data> 
  / 
  <span class="p-size">17.41mb</span>
</div>
```

> _[[17:53](https://chat.indieweb.org/dev/2019-08-08/1565286782453800)]_ huh. now that i'm digging more, i can't find where i got that dt-duration is appropriate for u-video/audio. not seeing it on microformats.org or the wiki

`duration` is [a property of the old hAudio object](http://microformats.org/wiki/haudio#Duration). That page also specifies it should use the ISO 8601 format that @gRegorLove is using. It was actually copied from [the old hCalendar](http://microformats.org/wiki/hcalendar).

Interesting enough, when [h-event]() added `dt-duration` (and backwards compatible parsing of hCalendar’s `duration` as `dt-duration`) it dropped all mention of what format to expect of the value. That is probably worth a separate [issue on microformats/h-event](https://github.com/microformats/h-event/issues).

---

I think the correct HTML+mf2 for marking up the play length of an audio/video segment should be:

```html
<time class="dt-duration" datetime="PT14M35S">14 minutes and 35 seconds</time>
```

The question then becomes how you would connect this with any one specific `u-audio` or `u-video` property. As there could be several of those. But that touches on some of the same points that have been raised around [poster frames for videos](https://indieweb.org/poster_frame).

**Comment by snarfed** [comment]
> > aaronpk's is integer seconds […]
>
> Where does @aaronpk do this?

i was just reporting this, which says he does: https://indieweb.org/podcast#How_to_podcast_with_h-feed . i hadn't actually checked his markup.

**Comment by jgmac1106** [comment]
Can we just pick? dt-duration sounds settled and p-size works...just be nice to pass an itunes validator with an mf2 podcast feed

**Comment by snarfed** [comment]
ok! thanks for the discussion all. i've deployed preliminary support for reading and writing `duration` mf2 (and `length` as an alias). input supports both integer seconds and ISO 8601 duration, but output is currently integer seconds, for the purely personal and subjective reason that ISO 8610 datetimes are fairly common but (in my wholly biased experience) ISO 8601 durations are much more rare, while integer seconds is fairly obvious and self explanatory. happy to switch if either the wild or standard converge on ISO 8601!

example: https://granary.io/url?input=html&output=rss&url=http%3A%2F%2Flatenighttoast.com%2F

**Comment by snarfed** [comment]
hmm, our examples of `p-size` in the wild are both human-readable strings, eg `62.2 MB`, but that may not work. all other places we need size, [notably RSS `length`](http://www.rssboard.org/rss-specification#ltenclosuregtSubelementOfLtitemgt), need the exact number of bytes, which we can't get from a human-readable string approximation.

i could `HEAD` the audio or video file URL and use the `Content-Length` header, but that's overly heavyweight for a format conversion, and that header isn't even always available.

any thoughts on what to do here?

**Comment by snarfed** [comment]
[discussed on #microformats.](https://chat.indieweb.org/microformats/2019-10-30#t1572442973666000) i'm tentatively going to start emitting a `<data>` element, so i can include both exact bytes and human-readable string, eg:

```html
<data class="p-size" value="1234">1KB</data>
```

(i already handle both variants in input.)

**Comment by snarfed** [comment]
done. tentatively closing. feel free to reopen or add any other thoughts!
