### ISSUE TITLE
Something weird is happening with unicode

### ISSUE THREAD

**Issue by myfreeweb** [snarfed/granary#171]
e.g. on https://granary.io/url?hub=https%3A%2F%2Fpubsubhubbub.superfeedr.com%2F&input=html&output=atom&url=https%3A%2F%2Funrelenting.technology%2F — what's happening with the encoding?

see https://github.com/myfreeweb/sweetroll2/issues/1

**Comment by snarfed** [comment]
ugh. thanks for reporting, and sorry for the trouble!

something weird indeed. looks like this may be some interaction between your site and granary. for comparison, here's a similar granary conversion from HTML to Atom with a unicode char that makes it through fine, afaict: https://granary.io/url?input=html&output=atom&url=https%3A%2F%2Fsnarfed.org%2F2019-06-29_37722

i noticed your site returns `Content-Type: text/html` and has a `<meta charset="utf-8">` tag in the HTML. that's fine, obviously, and granary should handle it, but maybe it isn't? i'll investigate more.

**Comment by myfreeweb** [comment]
Yeah, that makes sense, usually only browsers are smart enough to handle that. I'll fix the server config.

**Comment by snarfed** [comment]
finally fixed this on my end too. motivated a big (but good!) refactoring. thanks again for the nudge!
