### ISSUE TITLE
CLI tool

### ISSUE THREAD

**Issue by eadmaster** [snarfed/granary#182]
what about including a CLI tool that can be used e.g. to periodically sync posts between social networks?

**Comment by snarfed** [comment]
sure! sounds good. https://github.com/twitter/twurl is a good example, along with others. i don't personally plan to work on this, but i'd happily accept more detailed design ideas or PRs!

btw, synching in general is surprisingly difficult. it's a much bigger project than just a CLI tool. https://datatransferproject.dev/ and https://github.com/neotoma (RIP) are good example projects. lots more general background here: https://indieweb.org/sync

**Comment by eadmaster** [comment]
I've been using https://dlvrit.com/ for a while but it is a freemium/closed source service with restrictions so i am looking for alternatives.

**Comment by snarfed** [comment]
Tentatively closing, since I don't personally plan to work on this. Feel free to reopen if you do!
