### ISSUE TITLE
webhooks on comments?

### ISSUE THREAD

**Issue by gelinger777** [snarfed/granary#184]
Is it possible to implement a webhook on comments and block a user based on ban-words?

**Comment by snarfed** [comment]
if you mean https://granary.io/, it's not currently a service that does things in the background, and i currently have plans to make it one, so it can't do those on its own. however, you can definitely write code that uses it (via library or API) to do them yourself! at least, for some silos.

for webhooks, you'd periodically poll the posts or feeds that you're looking for comments on, and then make a request to your webhook when you find new ones.

for blocking users, granary can fetch users' twitter and mastodon block lists, but it can't currently block new users. you could definitely look for your banned words in posts and block them using the silos' APIs directly though. or if you're interested in adding blocking to granary for a silo, i'd happily help you with PRs!

**Comment by gelinger777** [comment]
@snarfed yes, I mean if i self-host it. I only look now for facebook . I need following. 

User authorise the app, and we save it's page or user token. Then when new comments come in under his page , they need to be analised somehow. If a comment involves profanity from the predefined list, this user has to be  banned ( Probably I need another Graph API call to be programmed by myself) . I search for a fast and easy solution. If you could help me with a direction, i would be grateful. I will write you an email. now.

**Comment by snarfed** [comment]
ah, sounds like this is for facebook. do you already have a facebook app with the permissions you need? reading other users' comments, blocking, etc? and you understand that you'll only get comment from other users who have also installed your app? facebook has famously locked down their API a lot in recent years, so you'll want to look at that up front. [some details here.](https://brid.gy/about#rip-facebook)

**Comment by snarfed** [comment]
otherwise, yes! you can definitely build that, and granary can help. [my previous comment](https://github.com/snarfed/granary/issues/184#issuecomment-581548673) has a design sketch you could follow.

**Comment by gelinger777** [comment]
So basically if a person did not installed the app, I as a page owner cannot parse the comments left under my page posts by a user? And cannot ban him?

**Comment by snarfed** [comment]
> So basically if a person did not installed the app, I as a page owner cannot parse the comments left under my page posts by a user?

right. [details here](https://developers.facebook.com/blog/post/2018/05/01/facebook-login-updates-further-protect-privacy/); search for _Additionally, other users' profile information and comments will not be returned..._

**Comment by gelinger777** [comment]
ok thanks.
