### ISSUE TITLE
Drop h-cards from Microformats feeds?

### ISSUE THREAD

**Issue by aaronpk** [snarfed/granary#192]
https://granary.io/url?input=html&output=atom&url=https%3A%2F%2Faaronparecki.com/

The Atom feed generated from the Microformats on my home page does not validate.

The first item in the Microformats of my home page is my primary `h-card`. It's marked up properly with `u-url` and `u-uid` matching my home page URL. The rest of the items on the page are `h-entry`s, and should be converted to Atom entries. The first item however ends up as a mostly empty Atom entry, which breaks some parsers and does not validate either.

I would recommend either dropping all unrecognized items from the generated Atom feed (converting only recognized ones like `h-entry`), or special-casing this type of situation where a home page feed of posts is not wrapped in an explicit `h-feed`.

**Comment by snarfed** [comment]
yup, understood. thanks for filing!
