### ISSUE TITLE
[reddit] Provide more info about the post

### ISSUE THREAD

**Issue by jamietanna** [snarfed/granary#213]
I.e. if the post links to an image/video, it'd be good to have the `photo` / `video` properties respectively (in MF2)

Or at least a `bookmark-of` the linked URL, if one is available

**Comment by snarfed** [comment]
interesting ideas! i like them. @stedn what do you think?

**Comment by stedn** [comment]
i'm not sure how to get the photo/video itself to store.  but adding a the url whenever there is one makes sense.  so that should go under the `bookmark-of` attr in the activitystream?

**Comment by jamietanna** [comment]
I should have a PR raised for this shortly 👍

(Originally published at: https://www.jvt.me/mf2/2020/10/gottg/)

**Comment by jamietanna** [comment]
Hmm, this doesn't seem to be working :thinking:

`https://granary.io/reddit/@me/@all/@app/dj4njd?format=mf2-json` does not return a `bookmark-of`. The AS2 does contain the `object.targetUrl`, but it doesn't seem to be mapped here correctly.

Shall I re-open this, or raise a new issue?

**Comment by snarfed** [comment]
@jamietanna thanks for the catch! reopening this sgtm.

**Comment by jamietanna** [comment]
@snarfed I don't have access to Granary's GCP console, only Bridgy's (or I'm looking in the wrong place). Mind checking if you can see if it's definitely deployed the latest release from `master` to the demo site?

Just to sanity check me, cause I can see `content` working on the MF2 side, but the `name` and `bookmark-of` aren't appearing :thinking:

Or if there's anything you can spot that may be causing issues here?

**Comment by jamietanna** [comment]
This actually appears to be the first time we've set a `bookmark` in this project - I wonder if we need to do some extra work to get it mapping correctly?

**Comment by snarfed** [comment]
thanks for looking at this! you have the same permissions for project id `granary-demo` as for `brid-gy`, so i'm not sure why the GCP console isn't working. this URL doesn't work for you? https://console.cloud.google.com/appengine?project=granary-demo&serviceId=default

regardless, master is deployed now, and i'm seeing the same thing as you. `https://granary.io/reddit/@me/@all/@app/d4njd?format=as1` seems ok, but `?format=mf2-json` only has `content`. i assume it does the same thing for you locally in dev_appserver.py?

**Comment by jamietanna** [comment]
Ah yeah I can see it now - I think my GCP skills are a bit lacking!

I'd been having some trouble locally with it - I've forgotten how to run it, as I keep hitting:

```
RuntimeError: Cannot use the Cloud Datastore Emulator because the packaged grpcio is incompatible to this system. Please install grpcio using pip
```

Because it's trying to use my Python2, which isn't set up fully in the venv. I've now set that up (based on the [oauth-dropins README](https://github.com/snarfed/oauth-dropins#troubleshootingfaq) which required installing pip into the gcloud container I'm running on) and got it running locally :+1:

I now seem to be getting two issues:

- first, static resources aren't populating
- secondly the reddit client details aren't being picked up, despite them being in the repo root :thinking:

```
AssertionError: Please fill in the reddit_app_key and reddit_app_secret files in your app's root directory.
```

**Comment by snarfed** [comment]
glad you're in and have dev_appserver mostly working now!

>     * first, static resources aren't populating

ugh, sorry, yeah, this is awkward right now. search for _static file assets_ on https://github.com/snarfed/granary/ to find the bit in the readme on getting those working.

>     * secondly the reddit client details aren't being picked up, despite them being in the repo root 🤔

oh! sorry, looks like that error message is misleading. it's actually looking for `reddit_app_key_local` and `reddit_app_secret_local`, https://github.com/snarfed/oauth-dropins/blob/master/oauth_dropins/reddit.py#L24-L29 , since reddit doesn't let you have more than one OAuth redirect URL. feel free to update the error message if you end up touching o-d!
