### ISSUE TITLE
Using PixelFed reports 500 server error

### ISSUE THREAD

**Issue by ScootRay** [snarfed/granary#232]
Just passing along. Holler if I can help debug. Thanks!

Ray

GET https://granary.io/pixelfed/267478200693690368/@all/@app/?format=atom&access_token=...&user_id=267478200693690368&instance=https://pixelfed.social/

500 Internal Server Error

The server has either erred or is incapable of performing the requested operation.

**Comment by snarfed** [comment]
Ugh, thanks for filing! Fixed.
