### ISSUE TITLE
Unescaped character in summary

### ISSUE THREAD

**Issue by jeremycherfas** [snarfed/granary#234]
I received an error about malformed RSS (via Granary).

The problem is in webmention 271 at https://webmention.herokuapp.com/user/sites/jeremycherfas.net

webmention.io sends `summary | "@jack I use the Johnson & Johnson 7 minute workout app on iOS."`

Granary converts that to

````
<title>@jack I use the Johnson &amp; Johnson 7 minute workout app on iOS.</title>
<summary>@jack I use the Johnson & Johnson 7 minute workout app on iOS.</summary>
````

It is the unescaped `&` in the summary that is causing the problem. Is there anything I can do?

Thanks

Jeremy

**Comment by snarfed** [comment]
Ugh, thanks for filing! Silly bug, should be an easy fix. Will do.

**Comment by snarfed** [comment]
Btw, I assume you mean Atom, since `summary` exists in Atom but not RSS, right? I fixed this for Atom, feel free to retry!

**Comment by jeremycherfas** [comment]
Yeah, sorry, it was Atom. Zapier called it RSS, and I'm sticking with that excuse.

I think the fix worked, so thanks very much.
