### ISSUE TITLE
h-entry not being found on homepage

### ISSUE THREAD

**Issue by singpolyma** [snarfed/granary#244]
I'm curious why granary cannot find my h-entries on https://blog.jmp.chat/ but finds them fine on eg http://blog.jmp.chat/b/august-newsletter-2021 which is almost the same markup produced by the same template.

**Comment by snarfed** [comment]
@singpolyma any progress debugging your markup?

**Comment by singpolyma** [comment]
Oh, woah. When I cut-paste my markup into pin13 it *also* finds everything. But not when it downloads the URL itself! What...

**Comment by snarfed** [comment]
Glad you figured it out!
