### ISSUE TITLE
Instagram example

### ISSUE THREAD

**Issue by 89z** [snarfed/granary#255]
Do you have any example code for Instagram? I found the tests, but they all seem to be using bogus info. I am just looking to get image URLs from a post

**Comment by snarfed** [comment]
Good question! The `get_activities()` API is the same for all sites, but you're right, [the docs](https://granary.readthedocs.io/) need more examples.

Here's example Instagram code if you're using the API:
```
from granary.instagram import Instagramig = Instagram(access_token='...')
posts = it.get_activities(activity_id='...')
```

and if you want to scrape their HTML with a `sessionid` cookie instead:
```
from granary.instagram import Instagram
ig = Instagram(scrape=True, cookie='...')
posts = it.get_activities(activity_id='...')
```
