### ISSUE TITLE
facebook: apply for read_stream permission

### ISSUE THREAD

**Issue by snarfed** [snarfed/granary#26]
as part of the v2.x api upgrade (see snarfed/bridgy#339), facebook is drastically tightening the `read_stream` permission, which we need to see your friends' posts. it's an [extended permission](https://developers.facebook.com/docs/facebook-login/permissions/v2.2#reference-extended), which means you have to go through their [review process](https://developers.facebook.com/docs/apps/review) to get it. worse, even then they're unlikely to grant it. from https://developers.facebook.com/docs/facebook-login/permissions/v2.2#reference-read_stream :

> This permission is granted to apps building a Facebook-branded client on platforms where Facebook is not already available. For example, Android and iOS apps will not be approved for this permission. In addition, Web, Desktop, in-car and TV apps will not be granted this permission.

my one hope is to claim that this is a demo for a developer tool/library, so normal users won't use it. i'm not holding my breath though. :/

the faint silver lining is that app owners automatically get `read_stream` for their own facebook accounts, so we can at least keep testing it, even if the demo doesn't let other people any more.

(snarfed/facebook-atom#2 is the same issue)

**Comment by snarfed** [comment]
one odd thing is that [bridgy](https://github.com/snarfed/bridgy) hasn't been approved for `read_stream` either, and it's now using the v2.2 api (snarfed/bridgy#339), and when it [asks for `read_stream` during signup](https://github.com/snarfed/bridgy/blob/master/templates/facebook_signup.html#L8), facebook [grants it, even to users who aren't owners of the facebook app](https://github.com/snarfed/bridgy/issues/339#issuecomment-70553541).

the one explanation i can think of is that FB is grandfathering in `read_stream` access for apps that were created before 4/30/2014, [as mentioned in this SO post](http://stackoverflow.com/questions/24378997#comment37725606_24378997). i can't find that mentioned anywhere on http://developers.facebook.com/ though.

related links:
https://developers.facebook.com/docs/apps/changelog
https://developers.facebook.com/docs/apps/review
https://developers.facebook.com/docs/apps/upgrading
https://developers.facebook.com/docs/facebook-login/permissions/v2.2

**Comment by asad1198** [comment]
can someone give me steps on how to grant permission to Read_stream please.

**Comment by snarfed** [comment]
@asad1198: short answer: you can't. :( if you use an app you own, you'll get it for your own account if you include `read_stream` in the oauth scopes you request during auth, but you won't get it for anyone else.

**Comment by snarfed** [comment]
facebook is gradually moving backward on us. `read_stream` was never really achievable, but they're [removing it and `/me/home` in API v2.4 altogether.](https://developers.facebook.com/docs/apps/changelog#v2_4_deprecations) whee!
