### ISSUE TITLE
audit mf2 conversion based on w3c's recommendations

### ISSUE THREAD

**Issue by snarfed** [snarfed/granary#28]
specifically https://www.w3.org/wiki/Activity_Streams/Microformats_Mapping

cc @tantek @elf-pavlik

**Comment by elf-pavlik** [comment]
we discussed on IRC the URL requirement for u-uid
http://indiewebcamp.com/irc/2015-03-03/line/1425433534250

**Comment by kylewm** [comment]
My interpretation is that UID "should" be a URL, not "must" be a URL.

This is a non-normative brainstorming page, but: http://microformats.org/wiki/uid-brainstorming#SHOULD_rather_than_MUST

**Comment by snarfed** [comment]
https://www.w3.org/wiki/Activity_Streams/Microformats_Mapping was last updated June 2016, so I'm not sure this is useful any more. Tentatively closing.
