### ISSUE TITLE
expose mf2 <=> atom conversions as service and UI

### ISSUE THREAD

**Issue by snarfed** [snarfed/granary#31]
...specifically https://granary-demo.appspot.com/ . code will be easy; UI will probably be the tricky part (if any).

thanks to @voxpelli and @kartikprabhu for the inspiration!

**Comment by snarfed** [comment]
so this is pretty much all UI, and it's not at all clear to me how to integrate it with the existing UI. i tried a couple things and neither was very good. I'm open to ideas!

**Comment by kartikprabhu** [comment]
@snarfed UI as in exposing it through a form? How about having a hfeed->atom link on the main page; then expose a form that takes a URL, looks for h-feed and spits out an atom+xml document?

**Comment by snarfed** [comment]
@kartikprabhu sure, a separate page would work, but it'd be a bit clunky. my current attempt integrates it with the existing form that's shown when you auth with one of the silos, which is better, but also a bit clunky.

...or maybe I'm overthinking it and shouldn't worry so much about the UI. :P

**Comment by kylewm** [comment]
Clearly you need a microformats nascar button!

![microformats-logo](https://cloud.githubusercontent.com/assets/950127/9697645/c7e68c5a-5349-11e5-9b34-5d88d87be090.png)

**Comment by snarfed** [comment]
omg i know you're joking but i am totally using that

**Comment by kylewm** [comment]
Was totally not joking!

**Comment by kylewm** [comment]
So yeah I was just thinking, microformats button would open up a form like you have for the other endpoints, but it would just have one query parameter for URL, and then would show output in the iframe like you have now.

**Comment by snarfed** [comment]
this is currently soft launched on https://granary-demo.appspot.com/ . it's not good enough - specifically, it only looks for mf2 (json/html) items at the top level, which doesn't really work - but it's a start.

**Comment by kylewm** [comment]
It works well for individual permalink pages, seems like it will be quite nice with h-feed support.

In case it's useful, in Woodwind I look for an h-feed anywhere on the page and parse that, or fall back to the top level items https://github.com/kylewm/mf2util/blob/master/mf2util/interpret.py#L198

**Comment by snarfed** [comment]
ah, good call, thanks. (and yet another reminder i should really be using mf2util already. :P)

**Comment by snarfed** [comment]
deployed!
