### ISSUE TITLE
add a location url for geo-tagged instagram photos

### ISSUE THREAD

**Issue by kylewm** [snarfed/granary#32]
I'm pretty sure the URL is just `https://instagram.com/explore/locations/{place-id}`

Note: For Twitter, Granary uses latitude and longitude to link to gmaps, but Instagram gives us venue name and id instead.

**Comment by snarfed** [comment]
:thumbsup: sounds good!

**Comment by snarfed** [comment]
huh. i originally thought it was because i was logged out, but even logged in, that example url https://instagram.com/explore/locations/520640/ 404s for me. do other ids work for you?

**Comment by kylewm** [comment]
Yep, all the ones I've seen in my feed work. Here's a few from the top

https://instagram.com/explore/locations/633066604/
https://instagram.com/explore/locations/256322495/
https://instagram.com/explore/locations/306998/

**Comment by snarfed** [comment]
cool, sgtm. thanks for doing this!

**Comment by kylewm** [comment]
Yeah! I'm unreasonably excited to have added location info to Woodwind
