### ISSUE TITLE
make sure revoked or expired Flickr access tokens fail gracefully

### ISSUE THREAD

**Issue by kylewm** [snarfed/granary#35]
Moving this to an issue so I don't forget. 

Ryan said:
> oh, btw, do Flickr access tokens expire? and i assume users can revoke our access. does this translate those into 401s so bridgy knows to disable the account cleanly?

**Comment by snarfed** [comment]
yup. they can definitely be revoked, at least, even if they don't expire. the translation code (if any) will go into `webutil. util. interpret_http_exception `.

**Comment by kylewm** [comment]
Response for a revoked token is
```
code: 200
body: {"message": "Invalid auth token", "code": 98, "stat": "fail"}
```

**Comment by kylewm** [comment]
Done and tested in https://github.com/snarfed/bridgy/commit/283ff63ad52233f6ecb5b27b3321298b43495b08

**Comment by snarfed** [comment]
yay thanks!
