### ISSUE TITLE
Empty links in conversion to Atom

### ISSUE THREAD

**Issue by voxpelli** [snarfed/granary#38]
Just tried the new MF2 to Atom conversion added in #31, but the resulting feed didn't include any links:

https://granary-demo.appspot.com/url?input=html&output=atom&url=https%3A%2F%2Fwebmention.herokuapp.com%2Fapi%2Fmentions%3Fformat%3Dhtml%26site%3Dvoxpelli.com

Converted MF2 markup comes from:

https://webmention.herokuapp.com/api/mentions?format=html&site=voxpelli.com

Parsing that pages shows the URL:s being parsed correctly – so it seems like this is a bug within granary itself:

http://pin13.net/mf2/?url=https%3A%2F%2Fwebmention.herokuapp.com%2Fapi%2Fmentions%3Fformat%3Dhtml%26site%3Dvoxpelli.com

**Comment by snarfed** [comment]
thanks for the details! I'll look soon.
