### ISSUE TITLE
treat posts with "name" as prefix of "content" as "notes" rather than articles

### ISSUE THREAD

**Issue by tantek** [snarfed/granary#41]
See steps 6 onward here: https://indiewebcamp.com/post-type-discovery#Algorithm

**Comment by snarfed** [comment]
agreed! i'm hoping @kylewm's https://github.com/kylewm/mf2util does this so i can ride on its coattails. :P

**Comment by kylewm** [comment]
Yay! I would absolutely endorse using or copying `mf2util.util.is_name_a_title` https://github.com/kylewm/mf2util/blob/master/mf2util/util.py#L205

I'm less sure that you'd want to use the higher-level `mf2util.interpret_feed` method. It transforms the standard mf2 data from a page into a simpler format that expects certain properties and value types. It's what I want for Woodwind and for doing stuff like fetching a reply context, but I'm not sure if it'll ever be general enough for converting to AS

**Comment by snarfed** [comment]
we started using `mf2util.post_type_discovery` as part of #81, so looks like this is already done! closing.
