### ISSUE TITLE
Add the tags to the message/tweet

### ISSUE THREAD

**Issue by fundor333** [snarfed/granary#416]
Taken from [a bridgy issue](https://github.com/snarfed/bridgy/issues/478)

From this example post:

example post: http://cweiske.de/tagebuch/ouya-tomb-raider.htm

parsed as mf2 (https://kylewm.com/services/mf2?url=http://cweiske.de/tagebuch/ouya-tomb-raider.htm):

``` json
{"items": [{
  "type": ["h-entry"],
  "properties": {
    "category": ["bigsuck", "games", "ouya"],
    "name": ["Playing Tomb Raider 1 on OUYA"],
...
```

The code return 

`Playing Tomb Raider 1 on #OUYA [#bigsuck #games]`

I thing about add a parameter to Source._content_for_create for return the content with or without the hashtags

**Comment by fundor333** [comment]
If you like the idea i will write a PR with the update and the tests for the new code

**Comment by snarfed** [comment]
Thank you for filing! Following up in https://github.com/snarfed/bridgy/issues/478

**Comment by snarfed** [comment]
I'm open to adding this to granary as an option to `create()` that gets passed to `_content_for_create()`! I'm still not quite sure if I'd add it to Bridgy though. Details in https://github.com/snarfed/bridgy/issues/478#issuecomment-1264734978

**Comment by fundor333** [comment]
Do you have an dict or ActivityStreams object for testing this new function?

**Comment by snarfed** [comment]
@fundor333 are you eventually hoping to use this in Bridgy Publish? If so, I'd love to hear what you think of https://github.com/snarfed/bridgy/issues/478#issuecomment-1264734978 and `p-bridgy-twitter-content` as an alternative! Docs: https://brid.gy/about#silo-content

**Comment by snarfed** [comment]
If you're interested in this just in granary, separate from Bridgy Publish, then here are a few example test objects with `tags`/`category`:

https://github.com/snarfed/granary/blob/4a42cdd49946fbcd346b424aa6750b837f28461f/granary/tests/test_twitter.py#L199-L258

https://github.com/snarfed/granary/blob/4a42cdd49946fbcd346b424aa6750b837f28461f/granary/tests/test_microformats2.py#L695-L726

https://github.com/snarfed/granary/blob/4a42cdd49946fbcd346b424aa6750b837f28461f/granary/tests/testdata/note_with_hashtag.as.json#L1-L8

https://github.com/snarfed/granary/blob/4a42cdd49946fbcd346b424aa6750b837f28461f/granary/tests/testdata/note_with_hashtag.mf2.json#L1-L7

**Comment by snarfed** [comment]
Tentatively closing in favor of `p-bridgy-twitter-content`. Feel free to reopen!
