### ISSUE TITLE
Reduce reliance on h-as-* types when converting mf2 to AS

### ISSUE THREAD

**Issue by kylewm** [snarfed/granary#45]
`h-as-*` types are unofficial vocab and should not be required for most cases. we should be able to determine the type from the parent property (e.g. comment:) rather than expecting h-as-comment type on the embedded object.

**Comment by snarfed** [comment]
:+1: :+1: :+1: 

extrapolating from this, we ideally need the post type discovery algorithm, right? and if we go down that road, we should just migrate to using mf2util, right?

I'm fully in support of both of those. plus we'd be able to drop a handful of other chunks of half baked mf2 handling code in favor of mf2util's real implementations, right?

let's do it!

**Comment by kylewm** [comment]
I'm going to call this one done :) We still allow `h-as-*` classes to override the detected type, and we still export them in generated html, but we don't need them on input anymore.
