### ISSUE TITLE
handle quote tweets

### ISSUE THREAD

**Issue by snarfed** [snarfed/granary#49]
granary currently renders [quote tweets](https://support.twitter.com/articles/20169873) with just the quoted tweet URL, which isn't great. e.g. [this tweet]():

<img width="575" alt="screen shot 2015-10-26 at 10 16 06 am" src="https://cloud.githubusercontent.com/assets/778068/10736510/9e6dbb38-7bca-11e5-8c22-f418504eb978.png">

is rendered as:

> Python everywhere! [twitter.com/obrizan/status…](https://twitter.com/obrizan/status/658583490468945920)

i'm not sure how we should render them, but ideally we'd fully render the quoted tweet's text, mentions, links, etc.

quote tweets can be [identified by the `quoted_status_id` field](https://dev.twitter.com/overview/api/tweets).

very lightly related to snarfed/bridgy#504.

**Comment by snarfed** [comment]
woo, this should actually be pretty easy. evidently the whole quoted tweet object is included in the `quoted_status` field.

twitter renders it in an `h-cite`/reply context style box below the actual tweet, and hides the quote tweet link _if_ it's at the end of the tweet text. we could just do the same.

**Comment by kylewm** [comment]
This is done already isn't it? e.g.,

```html

<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body>
<article class="h-entry h-as-note">
  <span class="p-uid">tag:twitter.com:688090950829215744</span>
  <time class="dt-published" datetime="2016-01-15T20:10:41+00:00">2016-01-15T20:10:41+00:00</time>
  <span class="p-author h-card">
    <a class="p-name u-url" href="https://twitter.com/Eldritchreality">A powerful cabbit</a>
    <img class="u-photo" src="https://twitter.com/Eldritchreality/profile_image?size=original" alt="" />
  </span>
  <a class="u-url" href="https://twitter.com/Eldritchreality/status/688090950829215744">https://twitter.com/Eldritchreality/status/688090950829215744</a>
  <div class="e-content p-name">  
  YOU LITERALLY ARE A MARKOV CHAIN, WTF?<br />
<a href="https://twitter.com/eldritch_ebooks/status/688073162672713728">twitter.com/eldritch_ebook…</a>
<p>
<a class="link" href="https://twitter.com/eldritch_ebooks/status/688073162672713728">
</a>
</p>
  </div>

<article class="h-cite h-as-note">
  <span class="p-uid">tag:twitter.com:688073162672713728</span>
  <time class="dt-published" datetime="2016-01-15T19:00:00+00:00">2016-01-15T19:00:00+00:00</time>
  <span class="p-author h-card">
    <a class="p-name u-url" href="https://twitter.com/eldritch_ebooks">eldritch_ebooks</a>
    <img class="u-photo" src="https://twitter.com/eldritch_ebooks/profile_image?size=original" alt="" />
  </span>
  <a class="u-url" href="https://twitter.com/eldritch_ebooks/status/688073162672713728">https://twitter.com/eldritch_ebooks/status/688073162672713728</a>
  <div class="e-content p-name">
  I just discovered that Markov chains were just a random walk with delusions of grandeur.
  </div>
</article>
</article>
</body>
</html>
  

```

**Comment by snarfed** [comment]
awesome, yes! then we just need to do atom and we can close this.
