### ISSUE TITLE
support jf2 (experimental)

### ISSUE THREAD

**Issue by snarfed** [snarfed/granary#50]
jf2 is a new experimental alternative JSON mf2 format: http://microformats.org/wiki/jf2

cc @aaronpk. related: https://github.com/indieweb/jf2-validator

**Comment by aaronpk** [comment]
I would definitely recommend waiting until there are a few other publishers before doing anything with this in Bridgy! I could see this being useful if an iOS/Android app wanted to consume Bridgy data though!

**Comment by snarfed** [comment]
heh, agreed, i don't intend to do anything with it in bridgy. just granary for now (if at all).

**Comment by snarfed** [comment]
tracking in #109.
