### ISSUE TITLE
Add new hub= parameter for specifying a PuSH hub

### ISSUE THREAD

**Issue by voxpelli** [snarfed/granary#53]
To retain any realtimeness of the source in the converted output there's two needed components: Discovery and pinging.

The discovery have to be provided by Granary, while the pinging can easily be done by the one specifying the feed – by either chaining it onto an original PuSH update or by pinging in some other way.

By allowing a new `&hub=https://pubsubhubbub.superfeedr.com/` and when that is specified include the required `rel-hub` and `rel-self` links in both HTTP headers and, when possible, in the output (mostly needed for Atom feeds) discovery would be solved and it would be possible to also consume the converted output in realtime and skip the polling.

**Comment by kylewm** [comment]
So I understand, Granary would literally just include an arbitrary `rel="hub"` and `rel="self"` in the generated output ... with the expectation that a third party will send pings on our behalf.

So for example, if I want to use Granary to proxy my Atom feed, I include on my site:

```
<link rel="alternate" type="application/atom+xml" href="https://granary-demo.appspot.com/url?input=html&output=atom&url=https%3A%2F%2Fkylewm.com&hub=https%3A%2F%2Fpubsubhubbub.superfeedr.com"  />
```

And when my site updates, I send a ping to Superfeedr with both the HTML and the proxied Atom URL? 
```
hub.mode=publish
&hub.url[]=https%3A%2F%2Fkylewm.com
&hub.url[]=https%3A%2F%2Fgranary-demo.appspot.com%2Furl%3Finput%3Dhtml%26output%3Datom%26url%3Dhttps%253A%252F%252Fkylewm.com%26hub%3Dhttps%253A%252F%252Fpubsubhubbub.superfeedr.com`
```
(tricky double-encoding there)

**Comment by voxpelli** [comment]
Exactly, that's what I'm thinking

**Comment by snarfed** [comment]
i started implementing this, but then realized...do we really want to make it an explicity granary query param? what if granary just used the `rel-hub` link in your html? that would work, right?

**Comment by voxpelli** [comment]
@snarfed Then Granary would also need to ping that hub with the URL of the Granary feed whenever the original feed has been updated and you probably rather wouldn't. Not all hubs support such pinging either, so to ensure that such pinging works you would probably be better of using a hub known to support pinging then. And then it's a lot of work for you.

By allowing a hub to be specified as a query param instead you make all of that work into the clients work instead.

**Comment by snarfed** [comment]
[lots more discussion in IRC today.](http://indiewebcamp.com/irc/2016-04-08#t1460124490233) i definitely still don't understand it, but @voxpelli is confident that sites would send a different `hub=` than they advertize in their own `rel-hub`, and that granary should only use the `hub=` one, not the `rel-hub`, so i believe him.

[this seems to be the crux of it:](http://indiewebcamp.com/irc/2016-04-08#t1460125739942)
> the difference is two:
> 1. it's explicit so one knows that the hub will be pinged [by the site]
> 2. the explicitly specified hub can be expected to handle a third-party URL like Granary, which not all hubs do

**Comment by kylewm** [comment]
At the risk of beating a dead horse, lemme expand on those two points a bit

1. The worst thing a feed can do is specify a hub and then not ping it when there are updates -- consumers will poll it way less frequently. Probably the vast majority of the time we'll want granary feeds not to specify a hub at all.
2. The WordPress plugin (PushPress?) is an example of this. It has a built-in, self-hosted hub, and doesn't handle arbitrary remote feeds.

**Comment by snarfed** [comment]
tentatively deployed pending PR #83 on https://granary-demo.appspot.com/ for this. feedback is welcome!
