### ISSUE TITLE
test_app fails because of messed up sys.path

### ISSUE THREAD

**Issue by kylewm** [snarfed/granary#57]
running `python -m unittest granary.test.test_source test_app.AppTest.test_url_activitystreams_to_json_mf2` fails because it thinks `import app` refers to `~/oauth-dropins/app.pyc` ... how did oauth-dropins get on the path at all??

I suspect the culprit is `webutil.handlers` which calls:

```
from google.appengine.ext.webapp import template
```

which imports `django.templates`, and Django stuff monkeys with the sys.path quite a bit.

**Comment by kylewm** [comment]
(I wonder if stuff like this is why nose and py.test exist...)

**Comment by kylewm** [comment]
oh man, it wasn't Django at all. I had /home/kmahan/projects/oauth-dropins in local/lib/python2.7/site-packages/easy-install.pth (probably from an earlier call to pip install -e). Removed the easy-install.pth file altogether and everything's peachy

**Comment by snarfed** [comment]
on man indeed. thanks for debugging. probably another vote for https://github.com/snarfed/bridgy/issues/443 !
