### ISSUE TITLE
Nostr: Bad Request response for datetime

### ISSUE THREAD

**Issue by gRegorLove** [snarfed/granary#578]
For https://granary.io/url?input=html&output=nostr&url=https%3A%2F%2Fgregorlove.com%2Fstream%2F I got a Bad Request error:

> Could not convert to nostr: time data '2023-08-11 15:32.0' does not match format '%Y-%m-%d %H:%M:%S.%f'

I believe it's [this post](https://gregorlove.com/2023/08/throwback-radio-radio/) which has dt-published `2023-08-11 15:32-0700`

**Comment by snarfed** [comment]
Woo, thanks for trying it, and for the report!
