### ISSUE TITLE
name is always present

### ISSUE THREAD

**Issue by singpolyma** [snarfed/granary#60]
https://github.com/snarfed/granary/blob/master/granary/twitter.py#L716 uses name (title) if present on articles, otherwise falls back to content.  However http://microformats.org/wiki/microformats2-parsing#parsing_for_implied_properties and specifically "else use the textContent of the .h-x for name" means there will basically *always* be a name, and it may be much less useful than the content (if we know the content).

Seems like we need something like https://github.com/kylewm/mf2util/blob/b11e4d2801a3f36435eb90738af91e53a6bae862/mf2util.py#L254 to handle this case.

**Comment by singpolyma** [comment]
Proposal:

```
diff --git a/granary/microformats2.py b/granary/microformats2.py
index be823db..9b8934a 100644
--- a/granary/microformats2.py
+++ b/granary/microformats2.py
@@ -274,13 +274,16 @@ def json_to_object(mf2):

   urls = props.get('url') and get_string_urls(props.get('url'))

+  name = get_text(prop.get('name'))
+  content_text = get_text(prop.get('content'))
+
   obj = {
     'id': prop.get('uid'),
     'objectType': as_type,
     'verb': as_verb,
     'published': prop.get('published', ''),
     'updated': prop.get('updated', ''),
-    'displayName': get_text(prop.get('name')),
+    'displayName': name if mf2util.is_name_a_title(name, content_text) else None,
     'summary': get_text(prop.get('summary')),
     'content': get_html(prop.get('content')),
     'url': urls[0] if urls else None,
```

**Comment by kylewm** [comment]
I think it is generally desirable to include "displayName" on all AS objects, just like we include "name" on all mf2 objects.

If granary returns an objectType "article", you can assume that name is meaningful as a separate title; otherwise, it's superseded by the content.

Nice find on the mf2util method :) The post type detection algorithm that granary uses to determine if something is an article vs. note uses it too.

**Comment by kylewm** [comment]
Here's the notion that it's sort of a general purpose name [from the AS 1.0 spec](http://activitystrea.ms/specs/json/1.0/#rfc.section.3.4):

> A natural-language, human-readable and plain-text name for the object. HTML markup MUST NOT be included. An object MAY contain a displayName property. If the object does not specify an objectType property, the object SHOULD specify a displayName.

**Comment by singpolyma** [comment]
Hmm, `json_to_object` includes both `verb` *and* `displayName` even though the former is from Activity and the latter from ActivityObject.  Activity has a `title` attribute which would suit for this purpose.

Inferring from the object type if we should pay attention to the title or not seems... error prone

**Comment by kylewm** [comment]
I'm very not an expert on ActivityStreams, so I'll defer to @snarfed on those points.

In general I would favor doing this kind of Facebook-specific behavior as close to the Facebook publishing code as possible (e.g. check `objectType == 'article'` or use `mf2util.is_name_a_title` in the actual Facebook publishing code, which is what I did for Flickr).

**Comment by singpolyma** [comment]
I'm actually primarily working on Twitter stuff, so definitely not Facebook-specific at all :)

The issue with relying on objectType that I just ran into (and, it turns out, that caused me to find this in the first place) is that a repost has objectType `activity` and really a repost might have a title or not.

**Comment by kylewm** [comment]
my comment about Facebook-specific behavior was in reference to https://github.com/snarfed/bridgy/issues/554#issuecomment-158512290

**Comment by singpolyma** [comment]
Sure.  This issue was initiated because of https://github.com/snarfed/granary/blob/master/granary/twitter.py#L716 and then https://github.com/snarfed/bridgy/issues/554#issuecomment-158512290 turned out to be relevant as well.

**Comment by singpolyma** [comment]
If we push it to the edges, then this one will fix my repost issue with Twitter:

```
diff --git a/granary/twitter.py b/granary/twitter.py
index f3adf40..fbabdf3 100644
--- a/granary/twitter.py
+++ b/granary/twitter.py
@@ -22,6 +22,7 @@ import socket
 import urllib
 import urllib2
 import urlparse
+import mf2util

 import appengine_config
 from appengine_config import HTTP_TIMEOUT
@@ -706,8 +707,8 @@ class Twitter(source.Source):
     """
     type = obj.get('objectType')
     summary = obj.get('summary')
-    name = obj.get('displayName')
     content = obj.get('content')
+    name = obj.get('displayName') if mf2util.is_name_a_title(obj.get('displayName'), content) else None
     base_url = self.base_object(obj).get('url')

     if type == 'note' or (base_url and (type == 'comment' or obj.get('inReplyTo'))):
```

And I can do a similar check in the code for https://github.com/snarfed/bridgy/issues/554

**Comment by snarfed** [comment]
thanks for working on this, guys! i haven't followed it in depth yet, and i often glaze at standards-details work like this (mf2, AS, post type discovery, etc) and defer to @kylewm.

in general, i like to try to keep the format conversions like mf2 => AS as conservative as possible while still keeping as much of the source data as possible. it's nice to keep them as close to dumb schema mappings as possible.

ideally, any "judgment call" logic for deciding what's best/more appropriate to publish would be part of the create/preview code paths in granary or bridgy, not the format conversions.

as for the specific details, i trust you both. @singpolyma feel free to send PRs even if they're just speculative! definitely easier and more idiomatic onn github than diffs.

**Comment by kylewm** [comment]
@singpolyma I'm a bit confused what problem you are trying to solve for twitter. For notes and replies, it uses `summary or content or name`. so it shouldn't matter whether it has a name.

**Comment by singpolyma** [comment]
@kylewm when it's a repost it's not a note or reply, so it uses `summary or name or content`
