### ISSUE TITLE
_content_for_create may return HTML

### ISSUE THREAD

**Issue by singpolyma** [snarfed/granary#61]
`Twitter._content_for_create` may return HTML since it uses obj.get('content') when there is no summary or name and content is got as HTML.  However the rest of the code for create seems to assume it will always be plain text and proceed as such.  Some sort of HTML to text conversion (at the very least stripping tags and decoding entities) seems to be in order.

**Comment by singpolyma** [comment]
The HTML to text algorithm I use in my local aggregator (in ruby, certainly not perfect) for reference: https://gist.github.com/singpolyma/38d945d0e7a7dccb160d

**Comment by singpolyma** [comment]
This also affects Facebook publish.

**Comment by kylewm** [comment]
The conversion/preprocessing actually happens in Bridgy before it gets sent to Granary https://github.com/snarfed/bridgy/blob/master/publish.py#L362

**Comment by singpolyma** [comment]
@kylewm ah, ok, so granary expects that all of them are text by the time it sees them.  Thanks.

**Comment by kylewm** [comment]
Sure thing! I agree that is not very intuitive.
