### ISSUE TITLE
track and implement W3C Social API

### ISSUE THREAD

**Issue by snarfed** [snarfed/granary#63]
Social API is an emerging W3C standard API for interacting with social data and services...? looks like it could be a/the successor to the [OpenSocial API](http://opensocial-resources.googlecode.com/svn/spec/2.0.1/Social-API-Server.xml#ActivityStreams-Service), which granary's python API and REST service currently largely implement.

* http://w3c-social.github.io/SocialAPI/socialapi
* https://github.com/w3c-social/SocialAPI/blob/gh-pages/socialapi.md

this is mostly just a tracking issue for now until Social API is more fleshed out, but it's interesting to follow. cc @rhiaro, feel free to correct anything here.

**Comment by akuckartz** [comment]
:+1:

**Comment by snarfed** [comment]
i actually misunderstood that Social API draft. it's not  a new API, but an overview comparison of existing APIs in the space, including ActivityPump, micropub + webmention, SoLiD, PuSH, etc.


sooo... I'm going to close this. move along, nothing to see here.
