### ISSUE TITLE
set up and run as2test

### ISSUE THREAD

**Issue by snarfed** [snarfed/granary#64]
on the agenda of the social WG F2F today: https://www.w3.org/wiki/Socialwg/2015-12-01 
- https://github.com/w3c-social/as2test
- https://github.com/evanp/as2test

not sure which is canonical. cc @w3c-social, @evanp, etc.

**Comment by snarfed** [comment]
as background, our current data-driven tests are in https://github.com/snarfed/granary/tree/master/granary/test/testdata , and additional unit tests are in https://github.com/snarfed/granary/tree/master/granary/test .

**Comment by evanp** [comment]
@snarfed the w3c-social one is.

**Comment by snarfed** [comment]
as2test expects libraries to be able to generate and parse AS2 objects based on arbitrary command line parameters. granary is a converter, not a general purpose generator or parser, so this isn't really in its wheelhouse.
