### ISSUE TITLE
Exclude boosts and replies from @friends feed

### ISSUE THREAD

**Issue by mikae1** [snarfed/granary#655]
Granary is so close to giving me what I've always longed for — an atom feed of toots from everyone I follow.

This is possible with the `@friends` functionality, but it sadly includes all boosts and replies for those I follow which makes it unusable for me. I have this turned off in the Mastodon app and I really wish it was possible to disable boosts and replies for `@friends` in Granary too.

**Comment by snarfed** [comment]
Hey, thanks for the kind words! And you're in luck, granary already supports this! Just add `&shares=false` to the granary.io URL: https://github.com/snarfed/granary#using-the-rest-api

**Comment by mikae1** [comment]
> Just add `&shares=false` to the granary.io URL

Well thanks you, this is just awesome! 🙌
