### ISSUE TITLE
create: support posts with multiple pictures (Facebook)

### ISSUE THREAD

**Issue by snarfed** [snarfed/granary#67]
related to #66

silo status:
- [x] _Twitter_: done!
- [ ] _Facebook_: could do either explicit (new album) or implicit (multiple single-photo posts that FB will auto consolidate into one)
- [ ] _Flickr_: does this feature exist? i suspect no...?
-  _Google+_: no API support for publishing
-  _Instagram_: no API support for publishing

**Comment by kylewm** [comment]
I'd like to solve this for Facebook too, the mapping from multi-photo post to posse post is less clear. I guess multiple photos in a post would imply a new album?

**Comment by snarfed** [comment]
maybe! honestly I'm not familiar with Facebook's behavior here. I'd look at whether/how you can attach multiple pictures to a single status update, and try to handle and generate that.

**Comment by kylewm** [comment]
ohhh boy, looks like it adds them to the Timeline Photos album and creates a clustered post with a caption!

![multi-photo-post](https://cloud.githubusercontent.com/assets/950127/11770624/26b02e5a-a1b8-11e5-8fa9-fa1e9508f2d5.png)

(I'm amused that I accidentally caught the Gwen Stefani popup)

**Comment by snarfed** [comment]
I'm now dreading handling backfeed for both these posts and the automatic consolidated ones, snarfed/bridgy#562, correctly. :P

**Comment by tantek** [comment]
If you're looking for more examples of multi-photo posts, I could try coding support for one and publishing one tomorrow morning.

**Comment by snarfed** [comment]
done for twitter.

**Comment by snarfed** [comment]
Facebook posting API is dead (snarfed/bridgy#817), and it was the last silo we were seriously considering this for, so I'm closing. if anyone disagrees, feel free to say so.
