### ISSUE TITLE
mf2: handle posts with multiple pictures

### ISSUE THREAD

**Issue by snarfed** [snarfed/granary#68]
...converting to and from AS. related to #66 and #67.

silo status:
* [x] *Twitter*: `entities` and `extended_entities`
* [x] *Google+*: uses normal AS, [multiple elements in the `attachments` list field](https://developers.google.com/+/web/api/rest/latest/activities#object.attachments)
* [ ] *Facebook*: you can attach multiple pictures to a post, which afaict is different from a story generated by uploading multiple pictures to an album. however, the API only includes the first picture in the post object. `object_id` also points to just that first picture. i don't see any indication that there are more pictures. tried with both API v2.2 and v2.5. details below.
*  *Instagram*: doesn't exist
* *Flickr*: doesn't exist

facebook API post with multiple pictures, `/212038_10102112256023793`:
```json
{
  "id": "212038_10102112256023793",
  "object_id": "10102112255849143",
  "type": "photo",
  "status_type": "added_photos",
  "story": "Ryan Barrett added 2 new photos.",
  "name": "Photos from Ryan Barrett's post",
  "picture": "https://scontent.xx.fbcdn.net/hphotos-xaf1/v/t1.0-0/s130x130/12662507_10102112255849143_5073018125726488185_n.jpg?...",
  "link": "https://www.facebook.com/photo.php?fbid=10102112255849143&set=a.995695740593.2393090.212038&type=3",
  "..."
}
```

and the photo object from `object_id`, `/10102112255849143` :
```json
{
  "id": "10102112255849143",
  "link": "https://www.facebook.com/photo.php?fbid=10102112255849143&set=a.995695740593.2393090.212038&type=3",
  "picture": "https://scontent.xx.fbcdn.net/hphotos-xaf1/v/t1.0-0/s130x130/12662507_10102112255849143_5073018125726488185_n.jpg?...",
  "images": ["..."]
}
```

**Comment by snarfed** [comment]
twitter example for converting from AS to Atom (rendered in NewsBlur):

<img width="700" alt="screen shot 2016-02-02 at 3 26 19 pm" src="https://cloud.githubusercontent.com/assets/778068/12767976/76664606-c9c1-11e5-8a35-feb4e883d1c2.png">

vs twitter itself:

<img width="595" alt="screen shot 2016-02-02 at 3 27 35 pm" src="https://cloud.githubusercontent.com/assets/778068/12767988/84a0dfd8-c9c1-11e5-9a43-c55513563dfa.png">

**Comment by kylewm** [comment]
no multi photo posts on flickr

**Comment by snarfed** [comment]
huh. TIL that only the first photo in a tweet shows up in `entities.media`. the rest are in `extended_entities.media`. https://dev.twitter.com/overview/api/entities-in-twitter-objects#extended_entities

TMYK!

**Comment by snarfed** [comment]
k, i think this is wrapped up for all silos. details in the description, updated. tentatively closing.
