### ISSUE TITLE
Incorrect use of `atom:uri` element

### ISSUE THREAD

**Issue by imax9000** [snarfed/granary#752]
https://github.com/snarfed/granary/blob/main/granary/atom.py#L265

```py
  a = {
    'objectType': 'activity',
    'verb': _as1_value(entry, 'verb') or 'post',
    'id': _text(entry, 'id') or (obj['id'] if obj_elem is None else None),
    'url': _text(entry, 'uri') or (obj['url'] if obj_elem is None else None),
    'object': obj,
    'actor': _author_to_actor(entry, feed_author=feed_author),
    'inReplyTo': obj.get('inReplyTo'),
  }
```

[`atom:uri`](https://datatracker.ietf.org/doc/html/rfc4287#section-3.2.2) element doesn't do what you think it does. Correct way of getting a URL from an entry is `href` attribute of [`atom:link`](https://datatracker.ietf.org/doc/html/rfc4287#section-4.2.7) element.

**Comment by snarfed** [comment]
Ah, good catch thank you! `uri` is evidently for authors, which fortunately means this is generally a noop, since we're grabbing `link` here:

https://github.com/snarfed/granary/blob/e93dbd241f4c31d26a766b607b00e435b40b9a9f/granary/atom.py#L284

Still worth fixing though!
