### ISSUE TITLE
mf2 => atom: fill in title and author details

### ISSUE THREAD

**Issue by snarfed** [snarfed/granary#79]
cc @aaronpk who's now using this to serve aaronparecki.com's feeds.

**Comment by aaronpk** [comment]
oh does my feed not show author info? Must be because I fall under the last case of the authorship discovery algorithm. You may be interested in this: https://github.com/aaronpk/XRay/blob/master/lib/Formats/Mf2.php#L154

**Comment by snarfed** [comment]
nah, it's not your fault. granary just doesn't even try for non-silo sources yet.

**Comment by snarfed** [comment]
evidently the [authorship](https://indiewebcamp.com/authorship) and [representative hcard](http://microformats.org/wiki/representative-hcard-parsing) algorithms are currently aimed at individual entries, not feeds. we may not have a canonical way to find an h-feed's author. [currently under discussion in #indiewebcamp.](http://indiewebcamp.com/irc/2016-02-22#t1456177211129)

granary now uses `mf2util.find_author()`, which implements the authorship algorithm, which is close enough for now.

**Comment by kylewm** [comment]
Beware that find_author does not follow the "letter of the law"  of
either algorithm and is probably a bit more lax and a bit less thorough
