### ISSUE TITLE
Don't convert newlines to <br> when input is HTML

### ISSUE THREAD

**Issue by gRegorLove** [snarfed/granary#80]
Specifically when converting HTML to Atom, the feed ends up with extra `<br>` around the existing `<p>`.

**Comment by snarfed** [comment]
:+1:

**Comment by snarfed** [comment]
(PRs welcome too, of course!)

**Comment by snarfed** [comment]
notes to myself:
* the `<br>`s get added here](https://github.com/snarfed/granary/blob/master/granary/microformats2.py#L558)
* afaict we should keep converting newlines in `p-content`, but stop converting in `e-content`. background in snarfed/bridgy#446 and https://indiewebcamp.com/note#Indieweb_whitespace_thinking
  * do mf2 parsers propagate these into `content` => `text` vs `html`, respectively?
* i tried adding html2text here](https://github.com/snarfed/granary/blob/master/granary/microformats2.py#L84), which worked, but broke lots of other stuff.

**Comment by gRegorLove** [comment]
> do mf2 parsers propagate these into content => text vs html, respectively?

`e-content` parses into `value` and `html` keys, but `p-content` wouldn't—just the plaintext value. It seems it would be safe to convert newlines in all instances except when the key is `content => html`

**Comment by snarfed** [comment]
belated: the actual fix commit was 795252eddfcf9592e466c4b2421c1ba44928e6e5
