### ISSUE TITLE
Include person tags and venue data

### ISSUE THREAD

**Issue by aaronpk** [snarfed/granary#92]
Person tags and venue data appear in the JSON blob on the photo permalinks.

To get the actual coordinates of the venue, you can use this URL given a venue ID:

`https://www.instagram.com/explore/locations/610388922/`

The coordinates are in HTML meta tags:

```
                <meta property="place:location:latitude" content="37.486662" />
                <meta property="place:location:longitude" content="-122.228468" />
```

**Comment by aaronpk** [comment]
It appears the venue permalink I found only works from a logged-in request

**Comment by aaronpk** [comment]
I spoke too soon! It is empty unless there is a referer header set!

**Comment by snarfed** [comment]
aha, figured out what's happening here. granary does actually understand and convert location and person tags, but they're only in the individual photo/video pages' JSON data, not in profile pages, so you can't get them from the interactive form on https://granary-demo.appspot.com/ . i'll see about adding them there.

**Comment by snarfed** [comment]
in the meantime, here's an example REST API link that includes location:
https://granary-demo.appspot.com/instagram/aaronpk/@self/@app/1258298747550288618_1500881?format=json-mf2

```json
"location": [{
    "type": ["h-card", "p-location"],
    "properties": {
      "url": ["https://instagram.com/explore/locations/956771335/"],
      "uid": ["956771335"],
      "name": ["WeWork Custom House"]
    }
}]
```

**Comment by snarfed** [comment]
here's another with person tags...but they only show up in AS output, not mf2. i'll fix that.
https://granary-demo.appspot.com/instagram/thejohnnysmith/@self/@app/1020355224898358984_654594

```json
"tags": [
  {
    "username": "snarfed",
    "id": "tag:instagram.com:snarfed",
    "objectType": "person"
  }, {
    "username": "bossman713rd",
    "id": "tag:instagram.com:bossman713rd",
    "objectType": "person"
  },
  "..."
]
```

**Comment by aaronpk** [comment]
Just as a note, `["h-card", "p-location"]` is not valid mf2 JSON. You can just drop the `p-location` from that array.

**Comment by snarfed** [comment]
ah, the `p-location` is implied because it's inside the `location` property? sg, will do. thanks.

**Comment by aaronpk** [comment]
Yes, but more like the `p-location` *causes* the `h-card` to be on a property in the parent named `location`.

**Comment by snarfed** [comment]
heh, got it. that's the html => mf2 (ie parsing) logic, which most people's mf2 intuition probably comes from. granary goes the other direction: it generates json mf2 de novo, then renders it to html if/when necessary. probably why my own mf2 intuition is a bit different...and maybe why i've never really internalized it like you all. :P ah well!
