### ISSUE TITLE
Support ActivityStreams 2.0

### ISSUE THREAD

**Issue by rhiaro** [snarfed/granary#94]
AS2 is hitting CR and looking for implementations, so Granary supporting transforming silo feeds into AS2 would be a Good Thing. 

Related: #64

**Comment by snarfed** [comment]
noted! thanks for the nudge.

granary's AS output right now is somewhere between AS 1 and 2. specifically, it has a few useful AS2-isms like letting things be lists instead of individual (`object`, `image`, `url`, etc.), and uses some of the AS2 vocab and verbs, but definitely hasn't implemented the new AS2 structure. that...will take some work.

**Comment by kylewm** [comment]
I think you just need to add `@context` and you're good to go! :trollface:

**Comment by paulcmal** [comment]
Well, there's [a few more differences](https://www.w3.org/TR/activitystreams-core/#activitystreams-1.0), but nothing extravagant.

Also, [collection paging](https://www.w3.org/TR/activitystreams-core/#collections) is wonderful.

**Comment by snarfed** [comment]
bumping this up in priority a bit since I'm thinking about building a bridge between indieweb and activitypub.

**Comment by snarfed** [comment]
finished a first pass at this. currently supported: articles, notes, replies, likes, events, tags, attachments.

TODO: RSVPs, reposts aka [re]shares. @rhiaro any idea how those work in AS2? for RSVPs, Accept/Reject an invite? what if there's no invite? and i haven't found anything for repost/[re]share yet.

**Comment by rhiaro** [comment]
I've been using Accepts/Rejects with the object of the Event itself in the absence of an Invite, for RSVPs. For a while I was artificially generating Invites, but that was just clumsy and pointless.

Announce is used as repost.

I don't like either of these, but they were raised as issues and stayed as they are, so what can ya do.

**Comment by snarfed** [comment]
done! enough for ActivityPub in https://fed.brid.gy , at least.
