### ISSUE TITLE
Support converting h-feed to Atom with rel="author".

### ISSUE THREAD

**Issue by Zegnat** [snarfed/granary#98]
As [previously discussed on IRC](https://chat.indieweb.org/2016-10-01#t1475331096058000), trying to convert `tantek.com` to an Atom feed gives a feed without any authorship information. While we expected an upstream bug in [kylewm/mf2util](https://github.com/kylewm/mf2util), the problem does not seem to be with that library.

See kylewm/mf2util#14 for example parser output and a possible fix for granary.

**Comment by snarfed** [comment]
thanks for filing!
